### ISSUE TITLE
Warning EMOTICON_TEMPLATE.render

### ISSUE THREAD

**Issue by pixeldot84** [Fantomas42/django-emoticons#5]
How to fix this?

RemovedInDjango110Warning: render() must be called with a dict, not a Context.
EMOTICON_TEMPLATE.render(context).strip())

**Comment by Fantomas42** [comment]
No courtesy ?
No explanations on how to reproduce the issue ?

You think I'm your dog ?
Next time keep your energy and your "reports", my repository is not a trash can.

And FYI, the fix method is explained your issue... If you want to fix an issue, starts by learning to read...

**Comment by pixeldot84** [comment]
You're right too rude written. Sorry for that.

I only want to show warning, that your project will not work in Django 1.10. That's all.

**Comment by Fantomas42** [comment]
Fixed in https://github.com/Fantomas42/django-emoticons/commit/7e965bfac4ab624e048bdbfc8ae0970171e44617

**Comment by bilalba** [comment]
This fix gave error for Django 1.5

  File "/local/lib/python2.7/site-packages/emoticons/settings.py", line 153, in <module>
    EMOTICONS_COMPILED = compile_emoticons(EMOTICONS_LIST)
  File "/local/lib/python2.7/site-packages/emoticons/settings.py", line 138, in compile_emoticons
    EMOTICON_TEMPLATE.render(context).strip())
  File "/local/lib/python2.7/site-packages/django/template/base.py", line 138, in render
    context.render_context.push()
AttributeError: 'dict' object has no attribute 'render_context'

**Comment by Fantomas42** [comment]
Hello,

Maybe it's time to upgrade your django version.
Or use a less recent version of django-emoticons.

Regards
